### ISSUE TITLE
Unhashable type:  'matrix' when trying to use purity function

### ISSUE THREAD

**Issue by zclandry** [marinkaz/nimfa#47]
When I try to use the purity function with a fitted nmf model, using a list of numbers as the membership list, I receive the following error:

nmf.purity(classes)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-2cfed5142075>", line 1, in <module>
    nmf.purity(classes)
  File "/usr/local/lib/python2.7/dist-packages/nimfa/models/nmf.py", line 388, in purity
    [dmbs.setdefault(mbs[i], set()).add(i) for i in range(len(mbs))]
TypeError: unhashable type: 'matrix'

the nmf model was fitted using the Bd function.  "classes" is a plain python list.  The documentation asks for a list.  Does it need something else? How can this be fixed?

**Comment by marinkaz** [comment]
Thank you, this is fixed now.

**Comment by zclandry** [comment]
Could you update the version from PyPI to reflect this?  Also, there seems to be a similar problem with the "entropy" function.  See below for details:

nmf.entropy(classes)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-e0f0b43a31b9>", line 1, in <module>
    nmf.entropy(classes)
  File "/usr/local/lib/python3.7/dist-packages/nimfa/models/nmf.py", line 251, in entropy
    [dmbs.setdefault(mbs[i], set()).add(i) for i in range(len(mbs))]
  File "/usr/local/lib/python3.7/dist-packages/nimfa/models/nmf.py", line 251, in <listcomp>
    [dmbs.setdefault(mbs[i], set()).add(i) for i in range(len(mbs))]
TypeError: unhashable type: 'matrix'

**Comment by marinkaz** [comment]
The new version is available on PyPI. It fixes of entropy function and includes a few other enhancements. Thanks!
