### ISSUE TITLE
Unable to run examples.recommendations

### ISSUE THREAD

**Issue by asparagii** [marinkaz/nimfa#52]
Running the recommendations example doesn't work
```python
import nimfa.examples
nimfa.examples.recommendations.run()
```

```
Read MovieLens data set
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-6947a2ae96c5> in <module>
      1 import nimfa.examples
----> 2 nimfa.examples.recommendations.run()

~/.local/lib/python3.8/site-packages/nimfa/examples/recommendations.py in run()
     65     """
     66     for data_set in ['ua', 'ub']:
---> 67         V = read(data_set)
     68         W, H = factorize(V)
     69         rmse(W, H, data_set)

~/.local/lib/python3.8/site-packages/nimfa/examples/recommendations.py in read(data_set)
    103     fname = join(dirname(dirname(abspath(__file__))), "datasets", "MovieLens", "%s.base" % data_set)
    104     V = np.ones((943, 1682)) * 2.5
--> 105     for line in open(fname):
    106         u, i, r, _ = list(map(int, line.split()))
    107         V[u - 1, i - 1] = r

FileNotFoundError: [Errno 2] No such file or directory: '/home/michele/.local/lib/python3.8/site-packages/nimfa/datasets/MovieLens/ua.base'
```
Running the script directly doesn't work either
```
$ pwd
/home/michele/.local/lib/python3.8/site-packages/nimfa/examples

$ ls
all_aml.py      documents.py             __init__.py         orl_images.py  recommendations.py
cbcl_images.py  gene_func_prediction.py  medulloblastoma.py  __pycache__    synthetic.py

$ python recommendations.py 
Read MovieLens data set
Traceback (most recent call last):
  File "recommendations.py", line 133, in <module>
    run()
  File "recommendations.py", line 67, in run
    V = read(data_set)
  File "recommendations.py", line 105, in read
    for line in open(fname):
FileNotFoundError: [Errno 2] No such file or directory: '/home/michele/.local/lib/python3.8/site-packages/nimfa/datasets/MovieLens/ua.base'
```

I installed the library via pip,
`$ pip install --user nimfa`

```
$ python --version
Python 3.8.1
$ pip --version
pip 19.3 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by asparagii** [comment]
Nevermind, you have to download the dataset yourself. 
Anyway, the movielens link is broken: http://www.grouplens.org/node/12 redirects to https://grouplens.org/datasets/ so I'm not sure what should I download

**Comment by asparagii** [comment]
Ok, the permalink for the intended dataset is  https://grouplens.org/datasets/movielens/100k/
