### ISSUE TITLE
Lfnmf

### ISSUE THREAD

**Issue by zclandry** [marinkaz/nimfa#62]
Hello, 
I am receiving the following error when using the Lfnmf method (with nnsvd seed).  This data works fine with other methods (for instance NMF, LSNMF and SNMF):

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-cde6af940b4d>", line 83, in <module>
    fit = nmf()
  File "/home/<username>/.local/lib/python3.9/site-packages/nimfa/models/nmf.py", line 118, in __call__
    return self.factorize()
  File "/home/<username>/.local/lib/python3.9/site-packages/nimfa/methods/factorization/lfnmf.py", line 172, in factorize
    self.update()
  File "/home/<username>/.local/lib/python3.9/site-packages/nimfa/methods/factorization/lfnmf.py", line 239, in update
    w_1 = sum(self.H[k, j] * self.V[i, j] / (dot(self.W[i, :], self.H[:, j])[0, 0] + 1e-5)
  File "/home/<username>/.local/lib/python3.9/site-packages/nimfa/methods/factorization/lfnmf.py", line 239, in <genexpr>
    w_1 = sum(self.H[k, j] * self.V[i, j] / (dot(self.W[i, :], self.H[:, j])[0, 0] + 1e-5)
  File "/usr/local/lib/python3.9/dist-packages/numpy/matrixlib/defmatrix.py", line 193, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 1213 is out of bounds for axis 1 with size 1213

**Comment by zclandry** [comment]
Also -the user directory was removed from the paths above.  Do you have any idea what the cause of this bug may be?

**Comment by zclandry** [comment]
Is there any additional information that you might need to check this out?

**Comment by KingHaHaHai** [comment]
I had the same problem, was it successfully resolved?
